### ISSUE TITLE
Some path somewhere is broken

### ISSUE THREAD

**Issue by peerchemist** [virtualeconomy/codename_felix_frontend#16]
App does not load on gh-pages, even if all the relevant files are there. I guess some path somewhere is broken.

https://github.com/virtualeconomy/codename_felix_frontend/tree/gh-pages

**Comment by peerchemist** [comment]
99% it's about links:

https://maximorlov.com/deploying-to-github-pages-dont-forget-to-fix-your-links/

**Comment by peerchemist** [comment]
More info:

https://github.com/gitname/react-gh-pages/issues/3

**Comment by peerchemist** [comment]
@Haynar216 can you pls investigate this?

**Comment by jwzheng96** [comment]
solved in #24
