### ISSUE TITLE
gallery page

### ISSUE THREAD

**Issue by marijacin** [virtualeconomy/codename_felix_frontend#22]
missing black background, user address, share button, etc. 

![WeChat Image_20220129130953](https://user-images.githubusercontent.com/86068985/151662253-4c17f9d3-c95c-4804-8e43-4fb2201af415.png)
![Capture](https://user-images.githubusercontent.com/86068985/151662283-4141cebb-07bb-4c4b-a932-26f26195dbcf.JPG)

**Comment by marijacin** [comment]
https://codepen.io/silkine/pen/jldif

inspiration for UI

**Comment by Haynar216** [comment]
Fixed in #36
