### ISSUE TITLE
"Word already save" bug is still with us.

### ISSUE THREAD

**Issue by peerchemist** [virtualeconomy/codename_felix_frontend#4]
![image](https://user-images.githubusercontent.com/7818961/151354503-d4333372-e4b9-48af-8cd8-cf5336c83dee.png)

**Comment by jwzheng96** [comment]
The page jumping logic and the text of the button need to be further modified to ensure that it can support the saving of a single word.

**Comment by marijacin** [comment]
https://www.figma.com/file/pZSbxe9cktzcc52IHIlUy7/felix?node-id=0%3A1

here is the solution. 
![Capture](https://user-images.githubusercontent.com/86068985/151658951-437d351a-ea68-4edd-9c1f-3f3c77fe841f.JPG)

**Comment by Haynar216** [comment]
Done
